### PR TITLE
Merge dev-master into master branch

### PR DESCRIPTION
**Pull request by sdhutchins**
Addresses #62.

- Added class for parallel programming. 
- Added contributing doc.

### CODE REVIEW

**Comment by sdhutchins** [comment]
I removed that code climate integration. IDk how I added it @grabear 😢

**Comment by sdhutchins** [comment]
I'll fix these @grabear

**Comment by grabear** [comment]
There isn't anything wrong.  It just auto generated that Conflict list.  @sdhutchins

**Comment by sdhutchins** [comment]
I just opened it and was so confused. Lmao :pensive:

**Comment by grabear** [comment]
e2c8c6b failed but then the next commit (942c003) resolved it. @sdhutchins

**Comment by sdhutchins** [comment]
Okay. Cool. I'm done with this PR. I will probably have another by the am

**Pull request merged**
