### PR TITLE
Merge branch 'master' into DataMana-patch

### PR DESCRIPTION
**Pull request by grabear**

### CODE REVIEW

**Comment by grabear** [comment]
@sdhutchins this may fix the genbank.py issue

**Comment by sdhutchins** [comment]
It's certainly worth a try.

**Comment by sdhutchins** [comment]
https://help.github.com/articles/reverting-a-pull-request/

**Comment by sdhutchins** [comment]
@grabear [ff4555f](https://github.com/datasnakes/Datasnakes-Scripts/commit/ff4355ff50c1247296f5b9e2a886406f8513937a) needs to be reverted probably on the command line

**Pull request merged**
